const ROW_PER_PAGE = 8;

const SELECTED_OPTION_COLOR_CONFIG = {
  CORRECT: '#4cd137',
  INCORRECT: '#e74c3c',
};

const IGNORED_OPTION_OPACITY = 0.55;

const OPTION_COLOR_ARRAY = ['#0b59a1', '#00a2ae', '#f99903', '#ec3c71'];

export { ROW_PER_PAGE, SELECTED_OPTION_COLOR_CONFIG, IGNORED_OPTION_OPACITY, OPTION_COLOR_ARRAY };
