// env config
const BACKEND_ENDPOINT = import.meta.env.VITE_BACKEND_ENDPOINT;
const GOOGLE_OAUTH_CLIENT_ID = import.meta.env.VITE_GOOGLE_OAUTH_CLIENT_ID;
const VITE_ENDPOINT = import.meta.env.VITE_ENDPOINT;

export { BACKEND_ENDPOINT, GOOGLE_OAUTH_CLIENT_ID, VITE_ENDPOINT };
