namespace Examify.Core.Reponse;

public static class ResponseCodes
{
    public const string Success = "200";
    public const string Created = "201";
    public const string NoContent = "204";
    public const string BadRequest = "400";
    public const string Unauthorized = "401";
    public const string Forbidden = "403";
    public const string NotFound = "404";
    public const string MethodNotAllowed = "405";
    public const string Conflict = "409";
    public const string InternalServerError = "500";
    public const string NotImplemented = "501";
    public const string ServiceUnavailable = "503";
    public const string GatewayTimeout = "504";
    public const string UnknownError = "520";
    public const string InvalidToken = "401";
    public const string TokenExpired = "401";
    public const string TokenNotFound = "401";
    public const string TokenNotProvided = "401";
    public const string TokenInvalid = "401";
    public const string TokenRevoked = "401";
    public const string TokenAlreadyRevoked = "401";
    public const string TokenNotRevoked = "401";
    public const string TokenNotRevokedYet = "401";
    public const string TokenNotExpired = "401";
    public const string TokenAlreadyExpired = "401";
    public const string TokenNotExpiredYet = "401";
    public const string TokenNotValidYet = "401";
    public const string TokenInvalidSignature = "401";
    public const string TokenInvalidIssuer = "401";
    public const string TokenInvalidAudience = "401";
    public const string TokenInvalidLifetime = "401";
    public const string TokenInvalidAlgorithm = "401";
    public const string TokenInvalidType = "401";
    public const string TokenInvalidSubject = "401";
    public const string TokenInvalidClaim = "401";
    public const string TokenInvalidClaimValue = "401";
    public const string TokenInvalidClaimType = "401";
    public const string TokenInvalidClaimCount = "401";
    public const string TokenInvalidClaimDuplicate = "401";
    public const string TokenInvalidClaimMissing = "401";
    public const string TokenInvalidClaimEmpty = "401";
    public const string TokenInvalidClaimWhitespace = "401";
    public const string TokenInvalidClaimLength = "401";
    public const string TokenInvalidClaimPattern = "401";
    public const string TokenInvalidClaimRegex = "401";
    public const string TokenInvalidClaimRange = "401";
}